### PR TITLE
Make it possible to serve with the Flask server, without Elsa

### PR DESCRIPTION
**Pull request by encukou**
Squashed version of https://github.com/fedora-python/fedoralovespython.org/pull/26 with a change for .travis.yml

### CODE REVIEW

**Comment by encukou** [comment]
The rename is needed because `site` is a standard Python module, so our `site.py` can't be imported.

**Comment by nmilosev** [comment]
Thanks for the help!

**Comment by encukou** [comment]
I forgot that Miro's on vacation. I guess it doesn't make sense to wait for his review, so I merged it.

**Comment by hroncok** [comment]
+1 anyway

**Pull request merged**
