### PR TITLE
Don't point out Jython

### PR DESCRIPTION
**Pull request by encukou**
Jython packaging is not really something to be proud of :(

### CODE REVIEW

**Comment by hroncok** [comment]
We have the Jython logo in the picture for this point. Do you think that's fine?

**Comment by encukou** [comment]
Hm, that's right. We need 3+ implementations in Fedora...

**Comment by hroncok** [comment]
we have cpython, pypy and micropython.

**Comment by hroncok** [comment]
See https://github.com/fedora-python/fedoralovespython.org/pull/59

**Pull request closed without merging**
